/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Volumes/LokData/Clients/loklok-org/lights-keyboard/lights-keyboard-gui/public/4lights.glb -T -R 4096 -f avif -j -M -S --ratio 1.0 --output /Volumes/LokData/Clients/loklok-org/lights-keyboard/lights-keyboard-gui/public/output-compressed/glb_2.jsx 
Files: /Volumes/LokData/Clients/loklok-org/lights-keyboard/lights-keyboard-gui/public/4lights.glb [5.63MB] > /Volumes/LokData/Clients/loklok-org/lights-keyboard/lights-keyboard-gui/public/output-compressed/4lights-transformed.glb [216.22KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/4lights-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={3.37} decay={2} color="#007bff" position={[0.175, 0.19, -0.426]} />
      <pointLight intensity={3.37} decay={2} color="#29ff2c" position={[-0.272, 0.19, 0.241]} />
      <pointLight intensity={3.37} decay={2} color="#ff0000" position={[-0.236, 0.19, -0.401]} />
      <pointLight intensity={3.37} decay={2} color="#ff00a2" position={[0.194, 0.19, 0.03]} />
      <mesh geometry={nodes.Keys238.geometry} material={materials['keys.001']} position={[-0.339, 0.161, -0.544]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys239.geometry} material={materials['keys.001']} position={[0.31, 0.158, -0.547]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys240.geometry} material={materials['keys.001']} position={[0.093, 0.158, -0.547]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys241.geometry} material={materials['keys.001']} position={[-0.124, 0.158, -0.547]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys243.geometry} material={materials['keys.001']} position={[0.093, 0.16, -0.33]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys244.geometry} material={materials['keys.001']} position={[-0.125, 0.16, -0.33]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys245.geometry} material={materials['keys.001']} position={[-0.342, 0.16, -0.33]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys246.geometry} material={materials['keys.001']} position={[0.093, 0.161, -0.112]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys247.geometry} material={materials['keys.001']} position={[-0.125, 0.161, -0.112]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys248.geometry} material={materials['keys.001']} position={[-0.342, 0.161, -0.112]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys249.geometry} material={materials['keys.001']} position={[0.093, 0.163, 0.106]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys250.geometry} material={materials['keys.001']} position={[-0.125, 0.163, 0.106]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys251.geometry} material={materials['keys.001']} position={[-0.342, 0.163, 0.106]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys252.geometry} material={materials['keys.001']} position={[0.093, 0.165, 0.324]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys253.geometry} material={materials['keys.001']} position={[0.311, 0.162, 0.215]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys254.geometry} material={materials['keys.001']} position={[0.311, 0.159, -0.22]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.Keys255.geometry} material={materials['keys.001']} position={[-0.232, 0.165, 0.324]} rotation={[-0.007, 0, 0]} scale={[1, 1.079, 1.001]} />
      <mesh geometry={nodes.negative002.geometry} material={materials['keys.001']} position={[-0.016, 0.104, -0.106]} rotation={[0, 0, -Math.PI]} scale={[-0.453, 0.028, 0.567]} />
    </group>
  )
}

useGLTF.preload('/4lights-transformed.glb')
